name: Deploy (Server)

on:
    workflow_run:
        workflows: [CI (Server)]
        types: [completed]
        branches: [main]

defaults:
    run:
        working-directory: server

concurrency:
    group: server_deploy
    cancel-in-progress: false

jobs:
    deploy:
        name: Deploy
        if: ${{ github.repository == 'NachoToast/RimWorldModCatalogue' && github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Execute remote build process
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/RimWorldModCatalogue/server
                      chmod +x scripts/deploy.sh
                      ./scripts/deploy.sh
