name: Deploy

on:
    workflow_run:
        workflows: [CI]
        types: [completed]
        branches: [main]

concurrency:
    group: deploy
    cancel-in-progress: false

jobs:
    deploy:
        name: Deploy
        if: ${{ github.repository == 'NachoToast/RimWorldModCatalogue' && github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Execute remote build process
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/RimWorldModCatalogue
                      chmod +x scripts/deploy.sh
                      ./scripts/deploy.sh
