# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI (Server)

on:
    push:
        paths:
            - server/**

defaults:
    run:
        working-directory: server

jobs:
    build:
        name: Node
        runs-on: ubuntu-latest
        timeout-minutes: 5

        strategy:
            matrix:
                node-version: [16.x, 18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7

            - name: Setup Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install Dependencies
              run: pnpm install

            - name: Typecheck
              run: pnpm typecheck

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm run test
